#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM registry.fedoraproject.org/fedora-minimal AS build

RUN microdnf -y --setopt=install_weak_deps=False install gcc git python python-pandas qpid-proton-c-devel shadow-utils && microdnf clean all

RUN groupadd -r fritz && useradd -r -g fritz fritz
USER fritz
WORKDIR /home/fritz

RUN git clone --depth 1 https://github.com/ssorj/qbench.git

WORKDIR /home/fritz/qbench
RUN ./plano install

FROM registry.fedoraproject.org/fedora-minimal

RUN microdnf -y --setopt=install_weak_deps=False install python python-pandas qpid-proton-c shadow-utils sysstat && microdnf clean all

RUN groupadd -r fritz && useradd -r -g fritz fritz

COPY --chown=fritz:fritz --from=build /home/fritz/.local /home/fritz/.local

ENV PATH="/home/fritz/.local/bin:$PATH"
ENV PYTHONPATH="/home/fritz/.local/lib/python3.11"

USER fritz
WORKDIR /home/fritz
CMD ["/home/fritz/.local/bin/qbench", "server", "--host", "0.0.0.0", "--port", "55672"]
