FROM postgres

RUN apt-get -qq update > /dev/null
RUN apt-get -qq install postgresql-contrib > /dev/null

COPY init.sh /docker-entrypoint-initdb.d/init.sh

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
