FROM registry.fedoraproject.org/fedora-minimal

RUN microdnf install nginx && microdnf clean all

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.txt /app/web/index.txt

ENV HOME=/app

RUN touch /run/nginx.pid
RUN chown -R 1001:0 /app /etc/nginx /usr/share/nginx /var/lib/nginx
RUN chown -R 1001:0 /run/nginx.pid && chmod 664 /run/nginx.pid
RUN chown -R 1001:0 /var/log/nginx && chmod 775 /var/log/nginx

USER 1001
EXPOSE 8080

CMD ["/usr/sbin/nginx"]
