FROM registry.access.redhat.com/ubi9/ubi-minimal

RUN microdnf -y install java-17-openjdk-headless pip && microdnf clean all

RUN pip install pandas

COPY python/ /app/python
COPY subrepos/ /app/subrepos
COPY target/ /app/target

WORKDIR /app

CMD ["python", "python/main.py"]
